CREATE TABLE `tb_club_objective_progress` (
  `progress_id` INT NOT NULL AUTO_INCREMENT,
  `club_id` INT NOT NULL,
  `student_id` VARCHAR(17) NOT NULL,
  `academic_year` VARCHAR(4) NOT NULL,
  `academic_term` INT(1) NOT NULL,
  `obj_1` TINYINT(1) NOT NULL DEFAULT 0,
  `obj_2` TINYINT(1) NOT NULL DEFAULT 0,
  `obj_3` TINYINT(1) NOT NULL DEFAULT 0,
  `obj_4` TINYINT(1) NOT NULL DEFAULT 0,
  `obj_5` TINYINT(1) NOT NULL DEFAULT 0,
  `obj_6` TINYINT(1) NOT NULL DEFAULT 0,
  `obj_7` TINYINT(1) NOT NULL DEFAULT 0,
  `obj_8` TINYINT(1) NOT NULL DEFAULT 0,
  `obj_9` TINYINT(1) NOT NULL DEFAULT 0,
  `obj_10` TINYINT(1) NOT NULL DEFAULT 0,
  `total_passed` INT NULL,
  `objective_result` VARCHAR(10) NULL,
  `result_level` VARCHAR(10) NULL,
  `activity_notes` TEXT NULL,
  `correction_notes` TEXT NULL,
  `updated_by` VARCHAR(20) NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`progress_id`),
  INDEX `idx_club_student` (`club_id`, `student_id`, `academic_year`, `academic_term`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;
